
site_name: Project Honeypot Wiki
theme:
    name: readthedocs
    custom_dir: custom_theme/
    nav_style: dark
    logo: img/logo.png
    locale: en
    sticky_navigation: true
    prev_next_buttons_location: bottom