site_url: 
site_name: Project Honeypot Wiki
use_directory_urls: true
theme:
    name: readthedocs
    custom_dir: custom_theme/
    nav_style: dark
    logo: img/logo.png
    locale: en
    sticky_navigation: true
    prev_next_buttons_location: bottom
extra_css:
    - css/extra.css
markdown_extensions:
    - admonition
nav:
    - Github: 
        - Link: https://github.com/S-C-A-M-s/agdSlamJam2022-docs
    - Introduction: 
        - 'index.md'
    - Features: 
        - Main Features: 'main feats.md'
        - Traits:
            - CAFFINATED: 'traits/caf.md'
            - EXHAUSTED: 'traits/ex.md'
            - BUFF LEGS: 'traits/buff.md'
            - HISTORIAN: 'traits/hist.md'
            - ENABLER: 'traits/en.md'
            - MULTITASKER: 'traits/multi.md'
            - HARDENED CRIMINAL: 'traits/hard.md'
            - SMARTASS: 'traits/smart.md'
            - PIGLOVER: 'traits/pig.md'
            - WATER VESSEL EXPERT: 'traits/wat.md'
            - SAVIOR: 'traits/sav.md'
        - Locations:
            - Library: 'error.md'
            - Coffee Shop: 'error.md'
            - J-mart: 'error.md'
            - JFC: 'error.md'
            - Statue: 'error.md'
            - Botanic Gardens: 'error.md'
            - Pigs: 'error.md'
            - Trash: 'error.md'
            - Mall’s Balls: 'error.md'

